### ISSUE TITLE
Readme is out of date

### ISSUE THREAD

**Issue by skamensky** [cortezalegacy/corteza#2]
Looks lke the [corteza-webapp](https://github.com//cortezaproject/corteza-webapp) repo has been removed, archived, or privatized. Should the instructions be updated to indicate if this is still a metarepository?

I got the word meta repo from this image 
https://docs.cortezaproject.org/corteza-docs/2022.3/developer-guide/_images/build-pipelines.png

https://github.com/cortezaproject/corteza/blame/0fdcde346f19a5488d5baef44e12429dd2eaf647/README.md#L3-L6

**Comment by darh** [comment]
Will be addressed and solved after moving to monorepo https://github.com/orgs/cortezaproject/discussions/437
